export interface StarfishPayload {
  sessionId: string;
  studentName: string | null;
  riskScore: number;
  barriers: { code: string; severity: string; notes: string | null }[];
  caseSummary: string;
  nextSteps: string[];
}

const STARFISH_REASON_CODES: Record<string, string> = {
  FINANCIAL:        "Financial Concern",
  WORK:             "Work Obligation",
  FAMILY:           "Family Obligation",
  MENTAL_HEALTH:    "Personal/Medical",
  TRANSPORT:        "Transportation",
  HEALTH:           "Personal/Medical",
  DIGITAL_LITERACY: "Technology Access",
  IMMIGRATION_FEAR: "Other",
  MOTIVATION:       "Academic Concern",
  OTHER:            "Other",
};

export async function logToStarfish(payload: StarfishPayload): Promise<void> {
  const starfishApiUrl    = process.env.STARFISH_API_URL;
  const starfishApiKey    = process.env.STARFISH_API_KEY;
  const institutionId     = process.env.STARFISH_INSTITUTION_ID ?? "NOCE";

  const reasonCodes = payload.barriers.map((b) => ({
    code:     STARFISH_REASON_CODES[b.code] ?? "Other",
    notes:    b.notes ?? "",
    severity: b.severity,
  }));

  const starfishNote = [
    "[NOCE Navigator Suite — Automated Risk Alert]",
    `Risk Score: ${payload.riskScore}/100`,
    `Student: ${payload.studentName ?? "Anonymous"}`,
    "",
    "Case Summary:",
    payload.caseSummary,
    "",
    "Detected Barriers:",
    ...payload.barriers.map(
      (b) => `- ${STARFISH_REASON_CODES[b.code] ?? "Other"} (${b.severity}): ${b.notes ?? "No details"}`,
    ),
    "",
    "Recommended Interventions:",
    ...payload.nextSteps.map((s, i) => `${i + 1}. ${s}`),
    "",
    `Session ID: ${payload.sessionId}`,
    "Generated by: NOCE Navigator Suite AI",
  ].join("\n");

  if (!starfishApiUrl || !starfishApiKey) {
    // MOCK MODE — log exactly what would be sent to Starfish
    // eslint-disable-next-line no-console
    console.log("📋 [STARFISH MOCK] Would create case note:");
    // eslint-disable-next-line no-console
    console.log("  Institution:", institutionId);
    // eslint-disable-next-line no-console
    console.log("  Student:", payload.studentName ?? "Anonymous");
    // eslint-disable-next-line no-console
    console.log("  Reason codes:", reasonCodes.map((r) => r.code).join(", "));
    // eslint-disable-next-line no-console
    console.log("  Note preview:", starfishNote.slice(0, 200) + "...");
    // eslint-disable-next-line no-console
    console.log("✅ [STARFISH MOCK] Case note logged (mock mode — add STARFISH_API_URL + STARFISH_API_KEY to enable)");
    return;
  }

  // REAL MODE — uncomment when Starfish API credentials are available
  // try {
  //   await fetch(`${starfishApiUrl}/api/case-notes`, {
  //     method: "POST",
  //     headers: {
  //       "Authorization": `Bearer ${starfishApiKey}`,
  //       "Content-Type": "application/json",
  //       "X-Institution-Id": institutionId,
  //     },
  //     body: JSON.stringify({
  //       studentName: payload.studentName,
  //       reasonCodes: reasonCodes.map((r) => r.code),
  //       note: starfishNote,
  //       source: "NOCE Navigator Suite",
  //       sessionId: payload.sessionId,
  //     }),
  //   });
  //   console.log("✅ Starfish case note created for session:", payload.sessionId);
  // } catch (error) {
  //   console.error("❌ Starfish logging failed:", error);
  // }
}
